name: CI-CD                                      # nome do puipeline
on:                                              # disparar commit 
  push:                                          # dispara a triguer
    branches: ["main"]                           # disparar na main
  workflow_dispatch:                             # disparo manual
  
jobs:                                            # conjunto de tarefas
  CI:                                            # declara job de CI 
    runs-on: ubuntu-latest                       # onde vai executar no ubuntu
    steps:                                       # etapas, declarar os passos de execução abaixo
      - name: Exemplo                            # actions, as ações na sequencua
        run: echo "Hello World !!!!"             # conjunto de código executado de forma capsulada2

      - name: Checkout
        uses: actions/checkout@v4.2.2            
        
      - name: Docker to Docker Hub
        uses: docker/login-action@v3.4.0         # mostra onde esta esse codigo que irá executar repostorio
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}} # senha esta em settings em actiob  secrets
          password: ${{secrets.DOCKERHUB_TOKEN}}    #masfgroove 010246

          #action que vai construir a imagem
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: ./src
            push: true
            file: ./src/Dockerfile
            tags: |
               "masfgroove/nodejs-web:${{github.run_number}}"
               "masfgroove/nodejs-web:latest"  