name: CI-CD                                      # nome do puipeline
on:                                              # disparar commit 
  push:                                          # dispara a triguer
    branches: ["main"]                           # disparar na main
  workflow_dispatch:                             # disparo manual
  
jobs:                                            # conjunto de tarefas
  CI:                                            # declara job de CI 
    runs-on: ubuntu-latest                       # onde vai executar no ubuntu
    steps:                                       # etapas, declarar os passos de execução abaixo
      - name: Exemplo                            # actions, as ações na sequencua
        run: echo "Hello World !!!!" 
     
      
