name: CI-CD                                      # nome do pipeline
on:                                              # disparar commit 
  push:                                          # dispara o trigger
    branches: ["main"]                           # disparar na main
  workflow_dispatch:                             # disparo manual

jobs:                                            # conjunto de tarefas 
  CI:                                            # job de CI
    runs-on: ubuntu-latest                       # onde vai executar no ubuntu
    steps:                                       # etapas, declarar os passos de execução abaixo
      - name: Exemplo                            # exemplo de ação
        run: echo "Hello World !!!!"             # conjunto de código executado de forma capsulada

      - name: Checkout
        uses: actions/checkout@v3                # corrigido para versão estável do checkout
        
      - name: Docker login to Docker Hub
        uses: docker/login-action@v2              # versão mais estável do login
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}} # senha está em Settings > Secrets
          password: ${{secrets.DOCKERHUB_TOKEN}}    # token do Docker Hub

      # Ação de construção e push para Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3          # versão estável do build-push
        with:
          context: ./src                          # onde está o código fonte
          push: true
          file: ./src/Dockerfile                   # caminho para o Dockerfile
          tags: |
            "masfgroove/nodejs-web:${{github.run_number}}"  # tag única baseada no número do run
            "masfgroove/nodejs-web:latest"                  # tag "latest" 

  cd:                                            # job de CD
    runs-on: ubuntu-latest                       # onde vai executar no ubuntu
    needs: [CI]                                  # depende do job CI (só vai rodar após a CI)
    steps:
      - name: Checkout
        uses: actions/checkout@v3                # checkout do código fonte

      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v4           # ação para configurar o contexto do K8s
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}    # kubeconfig do Kubernetes armazenado como segredo

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5                 # ação de deploy no Kubernetes
        with:
          manifests: |                             # caminho para o arquivo de deployment YAML
            ./k8s/deployment.yaml               
          images: |                              # referência para a imagem no Docker Hub
            "masfgroove/nodejs-web:${{github.run_number}}"  
